Repository usdot-jpo-ode/wzdx, pull requests merged in 2020-09, with the labels that each got.

#87 Require restriction_type for a lane_restriction
  create-feed/schemas/wzdx_v3.0_feed.json
  spec-content/data-tables/lane_restrictions.md
Labels: v3

#88 Lowercase Time and Spatial Verification Enumerated Type Values
  create-feed/schemas/wzdx_v3.0_feed.json
  spec-content/README.md
  spec-content/data-tables/road_events.md
  spec-content/enumerated-types/spatial_verification.md
  spec-content/enumerated-types/time_verification.md
Labels: v3

#94 Clarify lane types and usage of lanes table
  README.md
  create-feed/examples/linestring_example.geojson
  create-feed/examples/multipoint_example.geojson
  create-feed/schemas/wzdx_v3.0_feed.json
  images/road_event_erd.png
  spec-content/README.md
  spec-content/data-tables/lanes.md
  spec-content/enumerated-types/derived-from-its-standards/lane_type.md
  spec-content/enumerated-types/lane_edge_reference.md
  spec-content/enumerated-types/lane_status.md
Labels: v3

#118 Identify both sequential and hierarchical relationships between road events and other entities
  README.md
  create-feed/examples/linestring_example.geojson
  create-feed/examples/multipoint_example.geojson
  create-feed/schemas/wzdx_v3.0_feed.json
  spec-content/README.md
  spec-content/data-tables/relationships.md
  spec-content/data-tables/road_events.md
Labels: v3

#117 Update metadata to allow multiple sources and include info directly in the feed, rather than an external file
  README.md
  create-feed/README.md
  create-feed/examples/linestring_example.geojson
  create-feed/examples/multipoint_example.geojson
  create-feed/schemas/wzdx_v3.0_feed.json
  images/feed_source_event_relationship.jpg
  images/road_event_erd.jpg
  images/road_event_erd.png
  spec-content/README.md
  spec-content/data-tables/metadata.md
  spec-content/data-tables/road_event_data_sources.md
  spec-content/data-tables/road_event_feed_info.md
  spec-content/data-tables/road_events.md
  spec-content/enumerated-types/location_method.md
Labels: v3

#119 Add "event_type" field to road event entity to accomodate detours (and more)
  README.md
  create-feed/examples/linestring_example.geojson
  create-feed/examples/multipoint_example.geojson
  create-feed/schemas/wzdx_v3.0_feed.json
  spec-content/README.md
  spec-content/data-tables/road_events.md
  spec-content/enumerated-types/event_type.md
Labels: v3

#89 Require major.minor format for road_event_feed_info `version` field
  create-feed/schemas/wzdx_v3.0_feed.json
  spec-content/data-tables/road_event_feed_info.md
Labels: v3

#107 Update root README
  README.md
Labels: All Co-Chair Approval, Non-spec

#127 Add "Tips for Testing and Validating a New Feed" section
  create-feed/README.md
Labels: Non-spec, Single Co-Chair Approval

#130 V3 SysEng Check Edits
  create-feed/README.md
  create-feed/schemas/wzdx_v2.0_feed.json
  create-feed/schemas/wzdx_v3.0_feed.json
  images/feed_source_event_relationship.jpg
  images/road_event_erd.drawio
  images/road_event_erd.jpg
  spec-content/README.md
  spec-content/data-tables/lanes.md
  spec-content/data-tables/road_event_data_sources.md
  spec-content/data-tables/road_event_feed_info.md
  spec-content/data-tables/road_events.md
Labels: v3

#132 Remove sub-repository bullet
  create-feed/README.md
Labels: Non-spec, Single Co-Chair Approval
