Repository usdot-jpo-ode/wzdx, pull requests merged in 2021-11, with the labels that each got.

#175 Deprecate lane_number
  create-feed/schemas/wzdx_v4.0_feed.json
  spec-content/objects/Lane.md
Labels: v4.0, Cleanup

#188 Refactor and clarify LaneType Enumerated Type
  create-feed/examples/linestring-examples/comprehensive_linestring_example.geojson
  create-feed/examples/linestring-examples/local_access_only_bidirectional_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario1_simple_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario2_laneshift_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario3_shoulder_bidrectional_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario4_detour_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario5_recurring_linestring_example.geojson
  create-feed/examples/multipoint-examples/comprehensive_multipoint_example.geojson
  create-feed/examples/multipoint-examples/local_access_only_bidirectional_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario1_simple_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario2_laneshift_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario3_shoulder_bidrectional_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario4_detour_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario5_recurring_multipoint_example.geojson
  create-feed/schemas/wzdx_v4.0_feed.json
  spec-content/enumerated-types/LaneType.md
Labels: v4.0, Refactor, New Functionality

#199 Location verify method
  create-feed/examples/linestring-examples/comprehensive_linestring_example.geojson
  create-feed/examples/linestring-examples/local_access_only_bidirectional_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario1_simple_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario2_laneshift_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario3_shoulder_bidrectional_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario4_detour_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario5_recurring_linestring_example.geojson
  create-feed/examples/multipoint-examples/comprehensive_multipoint_example.geojson
  create-feed/examples/multipoint-examples/local_access_only_bidirectional_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario1_simple_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario3_shoulder_bidrectional_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario4_detour_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario5_recurring_multipoint_example.geojson
  create-feed/schemas/wzdx_v4.0_feed.json
  spec-content/enumerated-types/SpatialVerification.md
  spec-content/objects/RoadEventDataSource.md
Labels: v4.0, Refactor

#174 Clarify that the value of reduced_speed_limit should be in kilometers per hour
  create-feed/schemas/wzdx_v4.0_feed.json
  spec-content/objects/RoadEvent.md
Labels: v4.0, Cleanup

#196 Additional vehicle_impact to enable real time field data
  create-feed/schemas/wzdx_v4.0_feed.json
  spec-content/enumerated-types/VehicleImpact.md
Labels: v4.0, New Functionality

#176 Remove object properties and enumerated types values that were deprecated in v3.1
  create-feed/examples/linestring-examples/scenario1_simple_linestring_example.geojson
  create-feed/examples/multipoint-examples/comprehensive_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario1_simple_multipoint_example.geojson
  create-feed/schemas/wzdx_v4.0_feed.json
  spec-content/enumerated-types/LaneStatus.md
  spec-content/objects/RoadEvent.md
  spec-content/objects/RoadEventFeature.md
Labels: v4.0, Cleanup

#177 Deprecate the lrs_type and lrs_url properties on the RoadEventDataSource object
  create-feed/examples/linestring-examples/comprehensive_linestring_example.geojson
  create-feed/examples/linestring-examples/local_access_only_bidirectional_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario1_simple_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario2_laneshift_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario3_shoulder_bidrectional_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario4_detour_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario5_recurring_linestring_example.geojson
  create-feed/examples/multipoint-examples/comprehensive_multipoint_example.geojson
  create-feed/examples/multipoint-examples/local_access_only_bidirectional_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario1_simple_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario2_laneshift_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario3_shoulder_bidrectional_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario4_detour_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario5_recurring_multipoint_example.geojson
  create-feed/schemas/wzdx_v4.0_feed.json
  spec-content/objects/RoadEvent.md
  spec-content/objects/RoadEventDataSource.md
Labels: v4.0, Cleanup

#198 Refactor Restrictions
  README.md
  create-feed/README.md
  create-feed/examples/linestring-examples/comprehensive_linestring_example.geojson
  create-feed/examples/linestring-examples/local_access_only_bidirectional_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario1_simple_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario3_shoulder_bidrectional_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario4_detour_linestring_example.geojson
  create-feed/examples/multipoint-examples/comprehensive_multipoint_example.geojson
  create-feed/examples/multipoint-examples/local_access_only_bidirectional_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario1_simple_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario3_shoulder_bidrectional_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario4_detour_multipoint_example.geojson
  create-feed/schemas/wzdx_v4.0_feed.json
  spec-content/README.md
  spec-content/enumerated-types/RestrictionType.md
  spec-content/enumerated-types/RoadRestriction.md
  spec-content/enumerated-types/UnitOfMeasurement.md
  spec-content/objects/Lane.md
  spec-content/objects/LaneRestriction.md
  spec-content/objects/Restriction.md
  spec-content/objects/RoadEvent.md
Labels: v4.0, Refactor, New Functionality

#206 Create new Worker Presence data structures
  README.md
  create-feed/examples/linestring-examples/comprehensive_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario1_simple_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario2_laneshift_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario3_shoulder_bidrectional_linestring_example.geojson
  create-feed/examples/linestring-examples/scenario4_detour_linestring_example.geojson
  create-feed/examples/multipoint-examples/comprehensive_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario1_simple_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario2_laneshift_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario3_shoulder_bidrectional_multipoint_example.geojson
  create-feed/examples/multipoint-examples/scenario4_detour_multipoint_example.geojson
  create-feed/schemas/wzdx_v4.0_feed.json
  spec-content/README.md
  spec-content/enumerated-types/WorkerPresenceConfidence.md
  spec-content/enumerated-types/WorkerPresenceDefinition.md
  spec-content/enumerated-types/WorkerPresenceMethod.md
  spec-content/objects/RoadEvent.md
  spec-content/objects/WorkerPresence.md
Labels: v4.0, Worker Presence, New Functionality
