Repository usdot-jpo-ode/wzdx, pull requests merged in 2021-03, with the labels that each got.

#157 Add license property to RoadEventFeedInfo
  create-feed/schemas/wzdx_vNext_feed.json
  images/wzdx_object_diagram.drawio
  images/wzdx_object_diagram.jpg
  spec-content/objects/RoadEventFeedInfo.md
Labels: Spring 2021 Release

#152 Add local-access-only restriction
  create-feed/schemas/wzdx_vNext_feed.json
  spec-content/enumerated-types/RoadRestriction.md
Labels: Spring 2021 Release

#148 Deprecate the total_num_lanes property on the RoadEvent object
  create-feed/README.md
  create-feed/examples/linestring_example.geojson
  create-feed/examples/multipoint_example.geojson
  create-feed/schemas/wzdx_vNext_feed.json
  spec-content/objects/RoadEvent.md
Labels: Spring 2021 Release

#147 Refactor LaneType enumeration to deprecate values that can be determined from other properties, such as order, status, and restrictions
  create-feed/examples/linestring_example.geojson
  create-feed/examples/multipoint_example.geojson
  create-feed/schemas/wzdx_vNext_feed.json
  spec-content/enumerated-types/LaneStatus.md
  spec-content/enumerated-types/derived-from-its-standards/LaneType.md
Labels: Spring 2021 Release

#145 Allow specifying a GeoJSON Bounding Box for the WZDxFeed and RoadEventFeature objects
  create-feed/schemas/wzdx_vNext_feed.json
  spec-content/objects/RoadEventFeature.md
  spec-content/objects/WZDxFeed.md
Labels: Spring 2021 Release

#150 Add road_names property to replace road_name and road_number
  create-feed/examples/linestring_example.geojson
  create-feed/examples/multipoint_example.geojson
  create-feed/schemas/wzdx_vNext_feed.json
  spec-content/objects/RoadEvent.md
Labels: Spring 2021 Release

#146 Move road event ID to from RoadEvent "road_event_id" to RoadEventFeature "id"
  create-feed/examples/linestring_example.geojson
  create-feed/examples/multipoint_example.geojson
  create-feed/schemas/wzdx_vNext_feed.json
  spec-content/objects/Relationship.md
  spec-content/objects/RoadEvent.md
  spec-content/objects/RoadEventFeature.md
Labels: Spring 2021 Release

#162 Add WZDx logos
  README.md
  images/wzdx_logo_blue_orange_x.eps
  images/wzdx_logo_blue_orange_x.png
  images/wzdx_logo_white_orange_x.eps
  images/wzdx_logo_white_orange_x.png
Labels: Non-spec, Simple, Single Approval

#164 Add WP Survey Report to documents
  documents/Work_Zone_Data_Survey_Report_2021-03-08.pdf
Labels: Non-spec, Simple

#166 Clean up HTML tag in a value of the RoadRestriction enumerated type in the spec
  spec-content/enumerated-types/RoadRestriction.md
Labels: Non-spec, Simple

#161 Clean up document names and hyperlinks
  README.md
  create-feed/README.md
  documents/WZDx_Data_Feed_Self-Validation_Checklist.docx
  documents/WZDx_Early_Adopters_Guide.pdf
Labels: Non-spec, Simple, Single Approval
