Repository usdot-jpo-ode/wzdx, pull requests merged in 2022-12, with the labels that each got.

#351 Mobile work zone
  examples/WorkZoneFeed/local_access_only_bidirectional_linestring_example.geojson
  examples/WorkZoneFeed/scenario1_simple_linestring_example.geojson
  examples/WorkZoneFeed/scenario1_simple_multipoint_example.geojson
  examples/WorkZoneFeed/scenario2_laneshift_linestring_example.geojson
  examples/WorkZoneFeed/scenario4_detour_linestring_example.geojson
  examples/WorkZoneFeed/scenario5_recurring_linestring_example.geojson
  schemas/4.1/RoadEventFeature.json
  spec-content/enumerated-types/WorkZoneType.md
  spec-content/objects/WorkZoneRoadEvent.md
Labels: New Functionality

#352 Allow providing current velocity for a field device
  schemas/4.2/DeviceFeed.json
  spec-content/objects/FieldDeviceCoreDetails.md
Labels: New Functionality

#353 Allow a LocationMarker to be used to mark an active work truck
  schemas/4.2/DeviceFeed.json
  spec-content/enumerated-types/MarkedLocationType.md
Labels: New Functionality

#354 Clarify FlashingBeacon is for representing a flashing warning beacon mounted on a temporary traffic control device
  schemas/4.2/DeviceFeed.json
  spec-content/README.md
  spec-content/enumerated-types/FieldDeviceType.md
  spec-content/objects/FlashingBeacon.md
Labels: Cleanup

#356 Add loops to Direction enumeration
  schemas/4.2/Direction.json
  spec-content/enumerated-types/Direction.md
Labels: New Functionality

#357 Update open/closed LaneStatus descriptions - Issue #237
  spec-content/enumerated-types/LaneStatus.md
Labels: Cleanup

#358 Clarify use of LineString and MultiPoint in road event geometry
  spec-content/objects/RoadEventFeature.md
Labels: Cleanup

#301 Docs/validation checklist update
  documents/README.md
  documents/WZDx_Data_Feed_Self-Validation_Checklist.docx
  documents/WZDx_Data_Feed_Self-Validation_Checklist_April2022.pdf
Labels: Non-spec

#362 Publish Worker Presence interviews lessons learned document
  documents/README.md
  documents/Worker_Presence_Interview_Lessons_Learned_2022-08.pdf
Labels: Worker Presence
