Repository usdot-jpo-ode/wzdx, pull requests merged in 2022-08, with the labels that each got.

#329 Change traffic sensor traffic data properties from Integer to Number value type (refactor to 4.1)
  schemas/4.1/SwzDeviceFeed.json
  spec-content/objects/TrafficSensor.md
  spec-content/objects/TrafficSensorLaneData.md
Labels: Smart Work Zones, Cleanup

#314 Rename center-left-turn-lane to be general to support more users
  examples/WZDxFeed/local_access_only_bidirectional_linestring_example.geojson
  schemas/4.1/RoadEventFeature.json
  spec-content/enumerated-types/LaneType.md
Labels: Refactor

#311 Allow LocationMarker to mark any delineation point in a work zone
  schemas/4.1/SwzDeviceFeed.json
  spec-content/enumerated-types/MarkedLocationType.md
Labels: Smart Work Zones, New Functionality

#313 Enable the Device Feed to describe temporary traffic signals
  schemas/4.1/SwzDeviceFeed.json
  spec-content/README.md
  spec-content/enumerated-types/FieldDeviceType.md
  spec-content/enumerated-types/MarkedLocationType.md
  spec-content/enumerated-types/TrafficSignalMode.md
  spec-content/objects/FieldDeviceCoreDetails.md
  spec-content/objects/FieldDeviceFeature.md
  spec-content/objects/TrafficSignal.md
Labels: Smart Work Zones, Refactor, New Functionality

#292 Add notes about HybridSign static_sign_text
  spec-content/objects/HybridSign.md
Labels: Non-spec, Simple, Smart Work Zones

#308 Allow specifying the sign text for a Flashing Beacon
  schemas/4.1/SwzDeviceFeed.json
  spec-content/objects/FlashingBeacon.md
Labels: Simple, Smart Work Zones, New Functionality

#309 Allow providing field device without providing a road name
  schemas/4.1/SwzDeviceFeed.json
  spec-content/objects/FieldDeviceCoreDetails.md
Labels: Simple, Smart Work Zones, Cleanup

#273 Add road_direction property to FieldDeviceCoreDetails
  examples/SwzDeviceFeed/arrow_board_ok_example.geojson
  examples/SwzDeviceFeed/camera_error_example.geojson
  schemas/4.1/Direction.json
  schemas/4.1/RoadEventFeature.json
  schemas/4.1/SwzDeviceFeed.json
  spec-content/enumerated-types/Direction.md
  spec-content/objects/FieldDeviceCoreDetails.md
Labels: Smart Work Zones, Cleanup

#278 Recommend UUIDs for identifiers and add "name" to RoadEventCoreDetails
  examples/RoadRestrictionFeed/bridge_height_restriction_linestring_example.geojson
  examples/WZDxFeed/local_access_only_bidirectional_linestring_example.geojson
  examples/WZDxFeed/scenario1_simple_linestring_example.geojson
  examples/WZDxFeed/scenario1_simple_multipoint_example.geojson
  examples/WZDxFeed/scenario2_laneshift_linestring_example.geojson
  examples/WZDxFeed/scenario3_shoulder_bidirectional_linestring_example.geojson
  examples/WZDxFeed/scenario4_detour_linestring_example.geojson
  schemas/4.1/FeedInfo.json
  schemas/4.1/RoadEventFeature.json
  schemas/4.1/SwzDeviceFeed.json
  spec-content/objects/FeedDataSource.md
  spec-content/objects/FieldDeviceFeature.md
  spec-content/objects/RoadEventCoreDetails.md
  spec-content/objects/RoadEventFeature.md
Labels: Refactor, New Functionality

#302 Clarify usage of update date
  schemas/4.1/RoadEventFeature.json
  schemas/4.1/SwzDeviceFeed.json
  spec-content/objects/FieldDeviceCoreDetails.md
  spec-content/objects/RoadEventCoreDetails.md
Labels: Cleanup

#306 Adding no-passing to RestrictionType
  schemas/4.1/RoadEventFeature.json
  spec-content/enumerated-types/RestrictionType.md
Labels: Refactor, New Functionality

#281 Use boolean properties for WorkZoneRoadEvent position verification
  examples/WZDxFeed/local_access_only_bidirectional_linestring_example.geojson
  examples/WZDxFeed/scenario1_simple_linestring_example.geojson
  examples/WZDxFeed/scenario1_simple_multipoint_example.geojson
  examples/WZDxFeed/scenario2_laneshift_linestring_example.geojson
  examples/WZDxFeed/scenario3_shoulder_bidirectional_linestring_example.geojson
  examples/WZDxFeed/scenario4_detour_linestring_example.geojson
  examples/WZDxFeed/scenario5_recurring_linestring_example.geojson
  schemas/4.1/RoadEventFeature.json
  spec-content/enumerated-types/SpatialVerification.md
  spec-content/objects/WorkZoneRoadEvent.md
Labels: Refactor, Cleanup

#294 Refactor and clarify event status and start/end date verification
  Creating_a_WZDx_Feed.md
  examples/WZDxFeed/local_access_only_bidirectional_linestring_example.geojson
  examples/WZDxFeed/scenario1_simple_linestring_example.geojson
  examples/WZDxFeed/scenario1_simple_multipoint_example.geojson
  examples/WZDxFeed/scenario2_laneshift_linestring_example.geojson
  examples/WZDxFeed/scenario3_shoulder_bidirectional_linestring_example.geojson
  examples/WZDxFeed/scenario4_detour_linestring_example.geojson
  examples/WZDxFeed/scenario5_recurring_linestring_example.geojson
  schemas/4.1/RoadEventFeature.json
  spec-content/README.md
  spec-content/enumerated-types/EventStatus.md
  spec-content/enumerated-types/TimeVerification.md
  spec-content/objects/DetourRoadEvent.md
  spec-content/objects/WorkZoneRoadEvent.md
Labels: Refactor, Cleanup

#291 Use the same property name for the FeedInfo object for all WZDx feeds
  examples/WZDxFeed/local_access_only_bidirectional_linestring_example.geojson
  examples/WZDxFeed/scenario1_simple_linestring_example.geojson
  examples/WZDxFeed/scenario1_simple_multipoint_example.geojson
  examples/WZDxFeed/scenario2_laneshift_linestring_example.geojson
  examples/WZDxFeed/scenario3_shoulder_bidirectional_linestring_example.geojson
  examples/WZDxFeed/scenario4_detour_linestring_example.geojson
  examples/WZDxFeed/scenario5_recurring_linestring_example.geojson
  schemas/4.1/WZDxFeed.json
  spec-content/objects/WZDxFeed.md
Labels: Cleanup

#293 Allow a LocationMarker to represent a device that is worn or carried by a worker
  schemas/4.1/SwzDeviceFeed.json
  spec-content/enumerated-types/MarkedLocationType.md
Labels: Smart Work Zones, New Functionality

#261 Remove "work zone" references in FeedDataSource object
  spec-content/objects/FeedDataSource.md
Labels: All Co-Chair Approval, Cleanup

#322 Refactor/relationship
  examples/README.md
  examples/WZDxFeed/scenario1_simple_linestring_example.geojson
  examples/WZDxFeed/scenario1_simple_multipoint_example.geojson
  examples/WZDxFeed/scenario3_shoulder_bidirectional_linestring_example.geojson
  examples/WZDxFeed/scenario4_detour_linestring_example.geojson
  examples/WZDxFeed/scenario5_recurring_linestring_example.geojson
  schemas/4.1/RoadEventFeature.json
  spec-content/README.md
  spec-content/enumerated-types/RelatedRoadEventType.md
  spec-content/objects/RelatedRoadEvent.md
  spec-content/objects/Relationship.md
  spec-content/objects/RoadEventCoreDetails.md
Labels: Refactor, New Functionality

#334 Rename SwzDeviceFeed to DeviceFeed
  Creating_a_WZDx_Feed.md
  README.md
  examples/DeviceFeed/arrow_board_ok_example.geojson
  examples/DeviceFeed/camera_error_example.geojson
  examples/README.md
  schemas/4.1/DeviceFeed.json
  spec-content/README.md
  spec-content/enumerated-types/WorkerPresenceConfidence.md
  spec-content/objects/DeviceFeed.md
  spec-content/objects/FeedInfo.md
  spec-content/objects/FieldDeviceCoreDetails.md
  spec-content/objects/FieldDeviceFeature.md
Labels: Non-spec, Smart Work Zones

#332 Migrate RoadRestrictionFeed content to new repository
  Creating_a_WZDx_Feed.md
  README.md
  examples/README.md
  schemas/4.1/RoadEventFeature.json
  schemas/4.1/RoadRestrictionFeed.json
  spec-content/README.md
  spec-content/enumerated-types/Direction.md
  spec-content/enumerated-types/EventType.md
  spec-content/enumerated-types/LaneStatus.md
  spec-content/enumerated-types/LaneType.md
  spec-content/enumerated-types/RestrictionType.md
  spec-content/enumerated-types/UnitOfMeasurement.md
  spec-content/enumerated-types/VehicleImpact.md
  spec-content/objects/FeedInfo.md
  spec-content/objects/Lane.md
  spec-content/objects/Restriction.md
  spec-content/objects/RestrictionRoadEvent.md
  spec-content/objects/RoadEventCoreDetails.md
  spec-content/objects/RoadEventFeature.md
  spec-content/objects/RoadRestrictionFeed.md
Labels: All Co-Chair Approval

#330 Add object diagrams for v4.1
  images/WZDx_DeviceFeed_object_diagram.drawio
  images/WZDx_DeviceFeed_object_diagram.png
  images/WZDx_WorkZoneFeed_object_diagram.drawio
  images/WZDx_WorkZoneFeed_object_diagram.png
  images/wzdx_object_diagram.drawio
  images/wzdx_object_diagram.jpg
  spec-content/README.md
Labels: Non-spec
