Repository usdot-jpo-ode/wzdx, pull requests merged in 2022-03, with the labels that each got.

#226 Fix project README 'Releases' section heading levels
  README.md
Labels: Non-spec, Single Approval

#240 Fix version number in SwzDeviceFeed examples
  examples/SwzDeviceFeed/arrow_board_ok_example.geojson
  examples/SwzDeviceFeed/camera_error_example.geojson
Labels: Non-spec, Single Approval, Simple

#265 v4.1 release setup
  Creating_a_WZDx_Feed.md
  README.md
  RELEASES.md
  schemas/4.1/BoundingBox.json
  schemas/4.1/FeedInfo.json
  schemas/4.1/RoadEventFeature.json
  schemas/4.1/RoadRestrictionFeed.json
  schemas/4.1/SwzDeviceFeed.json
  schemas/4.1/WZDxFeed.json
Labels: Non-spec, Single Approval, Simple

#260 Data security best practices
  Creating_a_WZDx_Feed.md
Labels: Non-spec, Simple, Technical Assistance

#280 Fix recurring event example feed
  examples/WZDxFeed/scenario5_recurring_linestring_example.geojson
Labels: Non-spec, Cleanup
